// PDF render WORKER — runs OUTSIDE Next's bundle (plain CommonJS), so @react-pdf/renderer and
// React resolve from node_modules as a SINGLE instance. This sidesteps the dual-React "error #31"
// that occurs when a Next-bundled document module (its own React) is handed to react-pdf's
// (node-resolved) reconciler. The parent (lib/pdf/render.ts) spawns this via worker_threads.
//
// Message in:  InvoiceData (the shape from invoice-document.tsx)
// Message out: { ok: true, base64 } | { ok: false, error }
const { parentPort } = require("worker_threads");
const { createElement: h } = require("react");
const { renderToBuffer, Document, Page, StyleSheet, Text, View } = require("@react-pdf/renderer");

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica", color: "#0a0a0a" },
  headerRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 24 },
  title: { fontSize: 22, fontFamily: "Helvetica-Bold" },
  muted: { color: "#737373" },
  metaRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 24 },
  metaBlock: { maxWidth: 240 },
  label: { fontSize: 8, color: "#737373", textTransform: "uppercase", marginBottom: 2, letterSpacing: 1 },
  value: { fontSize: 10, marginBottom: 6 },
  table: { borderTop: "1 solid #e5e5e5", marginTop: 8 },
  tr: { flexDirection: "row", borderBottom: "1 solid #e5e5e5", paddingVertical: 6 },
  thRow: { flexDirection: "row", borderBottom: "1 solid #0a0a0a", paddingBottom: 6 },
  cDesc: { flex: 4 },
  cQty: { flex: 1, textAlign: "right" },
  cUnit: { flex: 1.5, textAlign: "right" },
  cAmt: { flex: 1.5, textAlign: "right" },
  th: { fontSize: 8, color: "#737373", textTransform: "uppercase", letterSpacing: 1 },
  totalRow: { flexDirection: "row", justifyContent: "flex-end", marginTop: 12 },
  totalLabel: { width: 100, textAlign: "right", color: "#737373" },
  totalValue: { width: 90, textAlign: "right", fontFamily: "Helvetica-Bold" },
  footer: { position: "absolute", bottom: 32, left: 40, right: 40, fontSize: 8, color: "#737373", borderTop: "1 solid #e5e5e5", paddingTop: 8 },
});

function money(n, currency) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: currency || "USD" }).format(n);
}

function buildInvoiceElement(data) {
  const currency = data.currency || "USD";
  const total = data.items.reduce((s, i) => s + i.quantity * i.unitPrice, 0);
  return h(
    Document,
    { title: `Invoice ${data.number}` },
    h(
      Page,
      { size: "A4", style: styles.page },
      h(
        View,
        { style: styles.headerRow },
        h(View, null, h(Text, { style: styles.title }, "Invoice"), h(Text, { style: styles.muted }, `#${data.number}`)),
        h(View, { style: { textAlign: "right" } }, h(Text, { style: { fontFamily: "Helvetica-Bold" } }, data.from.name)),
      ),
      h(
        View,
        { style: styles.metaRow },
        h(
          View,
          { style: styles.metaBlock },
          h(Text, { style: styles.label }, "Bill to"),
          h(Text, { style: styles.value }, data.billTo.name),
          data.billTo.email ? h(Text, { style: styles.muted }, data.billTo.email) : null,
        ),
        h(
          View,
          { style: styles.metaBlock },
          h(Text, { style: styles.label }, "Issued"),
          h(Text, { style: styles.value }, data.issuedAt),
          data.dueAt ? h(Text, { style: styles.label }, "Due") : null,
          data.dueAt ? h(Text, { style: styles.value }, data.dueAt) : null,
        ),
      ),
      h(
        View,
        { style: styles.table },
        h(
          View,
          { style: styles.thRow },
          h(Text, { style: [styles.th, styles.cDesc] }, "Description"),
          h(Text, { style: [styles.th, styles.cQty] }, "Qty"),
          h(Text, { style: [styles.th, styles.cUnit] }, "Unit"),
          h(Text, { style: [styles.th, styles.cAmt] }, "Amount"),
        ),
        ...data.items.map((item, i) =>
          h(
            View,
            { style: styles.tr, key: i },
            h(Text, { style: styles.cDesc }, item.description),
            h(Text, { style: styles.cQty }, String(item.quantity)),
            h(Text, { style: styles.cUnit }, money(item.unitPrice, currency)),
            h(Text, { style: styles.cAmt }, money(item.quantity * item.unitPrice, currency)),
          ),
        ),
      ),
      h(
        View,
        { style: styles.totalRow },
        h(Text, { style: styles.totalLabel }, "Total"),
        h(Text, { style: styles.totalValue }, money(total, currency)),
      ),
      data.notes
        ? h(View, { style: { marginTop: 24 } }, h(Text, { style: styles.label }, "Notes"), h(Text, { style: styles.muted }, data.notes))
        : null,
      h(Text, { style: styles.footer, fixed: true }, `${data.from.name} · Generated by the platform · This is a placeholder invoice template.`),
    ),
  );
}

parentPort.on("message", async (data) => {
  try {
    const buffer = await renderToBuffer(buildInvoiceElement(data));
    parentPort.postMessage({ ok: true, base64: buffer.toString("base64") });
  } catch (err) {
    parentPort.postMessage({ ok: false, error: err && err.message ? err.message : String(err) });
  }
});
